import { CONNECTED_LOTTERY_PAGE_STATUS } from "~/lottery/declarations/state";

export const PAGE_STATUS_FOR_LOTTERY_TICKET_DIALOG = [
  CONNECTED_LOTTERY_PAGE_STATUS.SHOWING_TICKET,
  CONNECTED_LOTTERY_PAGE_STATUS.OFFERING_TO_OPEN_TICKET,
  CONNECTED_LOTTERY_PAGE_STATUS.OPENING_TICKET,
  CONNECTED_LOTTERY_PAGE_STATUS.OFFERING_TO_SEND_TICKET,
  CONNECTED_LOTTERY_PAGE_STATUS.SENDING_TICKET
] as const;
