import { RAW_METAMASK_ERROR_CODE, WEB3_ERROR_CODE } from "./declarations";

export const RAW_METAMASK_ERROR_CODE_TO_WEB3_ERROR_CODE: Record<
  RAW_METAMASK_ERROR_CODE,
  WEB3_ERROR_CODE | undefined
> = {
  [RAW_METAMASK_ERROR_CODE.ACTION_REJECTED]:
    WEB3_ERROR_CODE.USER_CANCELLED_OPERATION,
  [RAW_METAMASK_ERROR_CODE.INSUFFICIENT_FUNDS]:
    WEB3_ERROR_CODE.INSUFFICIENT_FUNDS
};

export const ERROR_CODES_TO_IGNORE: Set<WEB3_ERROR_CODE> = new Set([
  WEB3_ERROR_CODE.USER_CANCELLED_OPERATION
]);
